package com.example.dominantsoftdevelopment.model.enums;

import lombok.Getter;

import java.util.List;

@Getter
public enum Country {
    UZBEKISTAN(List.of(
            "Tashkent",
            "Andijon",
            "Buxoro",
            "Farg’ona",
            "Jizzax",
            "Xorazm",
            "Namangan",
            "Navoiy",
            "Qashqadaryo",
            "Samarqand",
            "Sirdaryo",
            "Surxondaryo",
            "")),

    KAZAKHSTAN(List.of(
            "Akmola",
            "Aktobe",
            "Almaty",
            "Astana",
            "Atyrau",
            "Baikonur",
            "East Kazakhstan",
            "Jambyl",
            "Jetisu",
            "Karaganda",
            "Kostanay",
            "Kyzylorda",
            "Mangystau",
            "North Kazakhstan",
            "Pavlodar",
            "Shymkent",
            "Ulytau",
            "West Kazakhstan"
    )),

    TAJIKISTAN(List.of(
            "Tashkent",
            "Dushanbe",
            "Badaxshon",
            "Sugʻd ",
            "Xatlon")),

    KYRGYZSTAN(List.of(
            "Bishkek",
            "Batken",
            "Jalal-Abad",
            "Naryn",
            "Osh",
            "Talas",
            "Karakol")),

    Turkey(List.of(
            "İzmir",
            "Samsun",
            "Ankara",
            "Van",
            "Istanbul",
            "Antalya",
            "Şanlıurfa")),

    Russia(List.of(
            "Mosk",
            "Sank",
            "Ady",
            "Alt",
            "Bashkortost",
            "B",
            "Dage",
            "Ingush",
            "Kab",
            "Kalmy",
            "Karachay",
            "Kare",
            "Komi Res",
            "Mariy E",
            "Mordo",
            "Sakh",
            "North Ossetia-Alaniya Respublikasi",
            "Tatarstan Respublikasi",
            "Tyva Respublikasi",
            "Udmurtiya Respublikasi",
            "Altay Krayi",
            "Krasnodar Krayi",
            "Krasnoyarsk Krayi",
            "Primorskiy Krayi",
            "Stavropol Krayi",
            "Zabaykalskiy Krayi",
            "Nenets Avtonom Respublikasi",
            "Khanty-Mansiyskiy Avtonom Respublikasi",
            "Chukotskiy Avtonom Respublikasi",
            "Yamalo - Nenetskiy Avtonom Respublikasi",
            "Adygeya",
            "Altay",
            "Astrakhan",
            "Belgorod",
            "Bryansk",
            "Vladimir",
            "Volgograd",
            "Vologda",
            "Voronezh",
            "Ivanovo",
            "Irkutsk",
            "Kaliningrad",
            "Kaluga",
            "Kamchatka",
            "Kemerovo",
            "Kirov",
            "Kostroma",
            "Kurgan",
            "Kursk",
            "Leningrad",
            "Lipetsk",
            "Magadan",
            "Moscow",
            "Murmansk",
            "Nizhniy Novgorod",
            "Novgorod",
            "Novosibirsk",
            "Omsk",
            "Orenburg",
            "Oryol",
            "Penza",
            "Pskov",
            "Rostov",
            "Ryazan",
            "Sakhalin",
            "Samara",
            "Saratov",
            "Smolensk",
            "Sverdlovsk",
            "Tambov",
            "Tomsk",
            "Tula",
            "Tver",
            "Tyumen",
            "Ulyanovsk",
            "Vladimir",
            "Volgograd",
            "Vologda",
            "Voronezh",
            "Yaroslavl",
            "Saint Petersburg")),
    Azerbaijan(List.of(
            "Bakı" ,
            "Abşeron" ,
            "Ağdam" ,
            "Ağdaş" ,
            "Ağcabədi" ,
            "Ağstafa" ,
            "Ağsu" ,
            "Astara" ,
            "Balakən" ,
            "Bərdə" ,
            "Beyləqan" ,
            "Biləsuvar" ,
            "Cəbrayıl" ,
            "Cəlilabad" ,
            "Daşkəsən" ,
            "Füzuli" ,
            "Gədəbəy" ,
            "Goranboy" ,
            "Gəncə" ,
            "Göyçay" ,
            "Hacıqabul" ,
            "İmişli" ,
            "İsmayıllı" ,
            "Kəlbəcər" ,
            "Kürdəmir" ,
            "Qəbələ" ,
            "Qax" ,
            "Qazax" ,
            "Quba" ,
            "Qubadlı" ,
            "Qusar" ,
            "Laçın" ,
            "Lənkəran" ,
            "Lənkəran" ,
            "Lerik" ,
            "Masallı" ,
            "Mingəçevir" ,
            "Naftalan" ,
            "Neftçala" ,
            "Oğuz" ,
            "Ordubad" ,
            "Qəbələ" ,
            "Qobustan" ,
            "Quba" ,
            "Qusar" ,
            "Saatlı" ,
            "Sabirabad" ,
            "Şəki" ,
            "Şəki" ,
            "Salyan" ,
            "Şamaxı" ,
            "Şamaxı" ,
            "Şərur" ,
            "Şirvan" ,
            "Siazan" ,
            "Sumqayıt" ,
            "Şuşa" ,
            "Tartar" ,
            "Tərtər" ,
            "Tovuz" ,
            "Ucar" ,
            "Xaçmaz" ,
            "Xızı" ,
            "Xocalı" ,
            "Xocavənd" ,
            "Yardımlı" ,
            "Yevlax" ,
            "Yevlax" ,
            "Zəngilan" ,
            "Zaqatala" ,
            "Zərdab" ));


    private final List<String> region;

    Country(List<String> region) {
        this.region = region;
    }

}
